languageCode = "ru-ru"
title = "Smile @rT's personal blog"
baseurl = "http://smileart.in.ua/"
theme = "hugo-theme-nix"

[params]
  GithubID = "smileart"
  TwitterID = "smileart"
  LinkedInID = "serge-bedzhyk"
  FacebookID = "smileart"
  InstagramID = "smileart"
  KeybaseID = "smileart"
  Name = "Serge Bedzhyk"
  HeaderUsername = "smileart"
  HeaderHostname = "smileart.in.ua"
  Email = "smileart21@gmail.com"
  About = "Ê•|âŠ™_Ê–âŠ™|Ê” â†’ web-developer ğŸ’» | reader ğŸ“– | gamerğŸ•¹ | curious geek ğŸ¤“ | and a fan of the UK ğŸ‡¬ğŸ‡§"
  ProfilePicture = "/img/shared/avatar.jpg"
  GoogleAnalytics = "UA-90567921-1"
  disqusShortname = "smileart-in-ua"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "projects"
    weight = 0
    url = "/projects"
